import Groq from "groq-sdk";

const groq = new Groq({
  apiKey: process.env.GROQ_KEY,
});

export async function main() {
  const chatCompletion = await getGroqChatCompletion();
  // Print the completion returned by the LLM.
  console.log(chatCompletion.choices[0].message.content || "");
}

export async function getGroqChatCompletion() {
  return groq.chat.completions.create({
    response_format: { type: "json_object" },
    temperature: 1, // this sets the randomness of the output generated by LLM [0,2]
    // stop : "Revamp", The output will be stopped if if encounters the word Revamp
    // max_completion_tokens : 1000, this will limit the LLM output to 1000 tokens
    messages: [
      {
        role: "system",
        content: `You are a emotion detector software, given a sentence, you will tell the emotion behind it and the scale (out of 10) of that emotion in JSON.
          For example : Input : I was so joyed today.
                        Output : {
                          "emotion" : "happy",
                          "scale" : 9
                        }
          `,
      },
      {
        role: "user",
        content:
          "Today the work at office was so hectic, I don't have any energy left in me.",
      },
    ],
    model: "llama-3.3-70b-versatile",
  });
}
main();
